-- MySQL Script generated by MySQL Workbench
-- Tue Jul 22 18:21:22 2014
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema task_list
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `task_list` ;
CREATE SCHEMA IF NOT EXISTS `task_list` DEFAULT CHARACTER SET utf8 ;
USE `task_list` ;

-- -----------------------------------------------------
-- Table `task_list`.`tasks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `task_list`.`tasks` ;

CREATE TABLE IF NOT EXISTS `task_list`.`tasks` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 66
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
